DROP TABLE IF EXISTS posts;CREATE TABLE posts (
    id INTEGER PRIMARY KEY,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    gameid INTEGER,
    tm INTEGER,
    mr INTEGER,
    gr INTEGER,
    am INTEGER,
    awm INTEGER,
    player TEXT NOT NULL
    );